import { useState } from "react";
import Sidebar from "../components/Sidebar";
import {
  CircleHelp,
  Radio,
  Cpu,
  BrainCircuit,
  TriangleAlert,
  BarChart3,
  Mail,
  Phone,
  BookOpen,
  Fish,
  ChevronDown,
  ChevronUp,
  Sparkles,
  ArrowRight
} from "lucide-react";

export default function HelpPage() {
  const [openFaqIndex, setOpenFaqIndex] = useState(null);

  const guides = [
    {
      icon: Radio,
      title: "IoT Simulator",
      description:
        "Simulate water quality parameters such as temperature, dissolved oxygen (DO), and pH to test system behavior.",
      color: "text-blue-650 bg-blue-50 border-blue-100",
      link: "/simulator"
    },
    {
      icon: Cpu,
      title: "Actuator Control",
      description:
        "Monitor and manually control pond actuators including aerators, feeders, and pumps.",
      color: "text-cyan-600 bg-cyan-50 border-cyan-100",
      link: "/actuator"
    },
    {
      icon: BrainCircuit,
      title: "AI Center",
      description:
        "View AI predictions, fish health assessments, and recommendations generated by NEELA AI.",
      color: "text-indigo-650 bg-indigo-50 border-indigo-100",
      link: "/ai-center"
    },
    {
      icon: TriangleAlert,
      title: "Alerts Page",
      description:
        "Receive notifications when abnormal water conditions or critical events are detected.",
      color: "text-rose-600 bg-rose-50 border-rose-100",
      link: "/alerts"
    },
    {
      icon: BarChart3,
      title: "Analytics Page",
      description:
        "Analyze historical data, decision trends, and overall aquaculture performance.",
      color: "text-amber-605 bg-amber-50 border-amber-100",
      link: "/analytics"
    },
  ];

  const faqs = [
    {
      question: "How often is sensor data updated?",
      answer: "Sensor values are updated in real time based on the connected IoT devices or simulator settings."
    },
    {
      question: "What does HIGH risk level mean?",
      answer: "HIGH risk indicates critical pond conditions that may affect fish health and require immediate action."
    },
    {
      question: "Can I manually override AI recommendations?",
      answer: "Yes. Operators can manually control actuators regardless of AI recommendations."
    },
    {
      question: "How is AI confidence calculated?",
      answer: "Confidence scores are estimated from the machine learning model performance and historical prediction consistency."
    },
  ];

  function toggleFaq(index) {
    setOpenFaqIndex(openFaqIndex === index ? null : index);
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="md:flex">
        <Sidebar />

        <main className="flex-1 p-6 md:p-10 max-w-7xl mx-auto w-full space-y-8">
          
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <div className="flex items-center gap-2">
                <div className="p-2 rounded-xl bg-blue-50 border border-blue-100 shadow-sm">
                  <CircleHelp className="w-6 h-6 text-[#1a6fc4] animate-pulse" />
                </div>
                <div>
                  <h1 className="text-3xl font-black text-slate-900 tracking-wide uppercase">
                    Help Center
                  </h1>
                  <p className="text-xs font-bold text-slate-450 uppercase tracking-widest mt-0.5">
                    Documentation, guides, and technical support
                  </p>
                </div>
              </div>
            </div>
            
            <div className="flex items-center gap-2">
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
                <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500" />
              </span>
              <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Support Portal Active</span>
            </div>
          </div>

          {/* BEST PRACTICE TIPS CARD */}
          <div className="bg-gradient-to-r from-[#1a6fc4] to-[#1e9bd4] text-white rounded-3xl p-6 md:p-8 shadow-xl shadow-blue-500/10 flex flex-col sm:flex-row sm:items-center justify-between gap-6 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-2xl pointer-events-none" />
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-2xl bg-white/10 text-white border border-white/20 flex-shrink-0 animate-bounce">
                <Fish className="w-8 h-8" />
              </div>
              <div>
                <h2 className="text-lg font-black uppercase tracking-wider flex items-center gap-1.5">
                  <span>Best Practice Guidelines</span>
                  <Sparkles className="w-4 h-4 text-cyan-300 fill-cyan-300" />
                </h2>
                <p className="text-xs text-white/80 leading-relaxed font-semibold mt-1 max-w-xl">
                  Monitor water quality regularly, respond quickly to alerts, and use AI explainability recommendations to optimize fish health and pond performance.
                </p>
              </div>
            </div>
          </div>

          {/* USER GUIDES SECTION */}
          <div className="bg-white rounded-3xl shadow-xl border border-slate-100 p-6 md:p-8">
            <div className="flex items-center gap-2 mb-6 pb-4 border-b border-slate-100">
              <BookOpen className="w-5 h-5 text-[#1a6fc4]" />
              <div>
                <h2 className="text-lg font-black text-slate-900 uppercase tracking-wide">
                  Application User Guides
                </h2>
                <p className="text-[10px] font-bold text-slate-450 uppercase tracking-widest mt-0.5">
                  Learn to manage components of the dashboard
                </p>
              </div>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
              {guides.map((guide) => {
                const Icon = guide.icon;
                return (
                  <div
                    key={guide.title}
                    className="p-5 rounded-2xl border border-slate-150 shadow-sm hover:shadow-md hover:border-[#1a6fc4]/20 hover:scale-[1.01] transition-all duration-300 flex flex-col justify-between"
                  >
                    <div>
                      <div className="flex items-center gap-3 mb-4">
                        <div className={`p-2.5 rounded-xl border ${guide.color} flex-shrink-0`}>
                          <Icon size={20} />
                        </div>
                        <h3 className="font-black text-sm text-slate-800 uppercase tracking-wide">
                          {guide.title}
                        </h3>
                      </div>
                      <p className="text-[11px] font-medium leading-relaxed text-slate-500 mb-6">
                        {guide.description}
                      </p>
                    </div>

                    <a
                      href={guide.link}
                      className="text-[9.5px] font-black uppercase text-[#1a6fc4] hover:text-[#1e9bd4] flex items-center gap-1 mt-auto"
                    >
                      <span>Navigate to module</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </a>
                  </div>
                );
              })}
            </div>
          </div>

          {/* FAQ SECTION WITH ACCORDIONS */}
          <div className="bg-white rounded-3xl shadow-xl border border-slate-100 p-6 md:p-8">
            <div className="mb-6 pb-4 border-b border-slate-100">
              <h2 className="text-lg font-black text-slate-900 uppercase tracking-wide">
                Frequently Asked Questions
              </h2>
              <p className="text-[10px] font-bold text-slate-450 uppercase tracking-widest mt-0.5">
                Quick answers to common questions about Neela AI
              </p>
            </div>

            <div className="space-y-4">
              {faqs.map((faq, index) => {
                const isOpen = openFaqIndex === index;
                return (
                  <div
                    key={faq.question}
                    className={`border border-slate-150 rounded-2xl transition-all duration-300 ${
                      isOpen ? "bg-[#f8fafc] border-[#1a6fc4]/20" : "bg-white"
                    }`}
                  >
                    <button
                      onClick={() => toggleFaq(index)}
                      className="w-full p-5 flex items-center justify-between gap-4 text-left font-black text-xs uppercase tracking-wider text-slate-800 cursor-pointer"
                    >
                      <span>{faq.question}</span>
                      <div className={`p-1 rounded-lg border ${isOpen ? "bg-blue-100/50 border-blue-200 text-[#1a6fc4]" : "bg-slate-50 border-slate-200 text-slate-400"} transition-all`}>
                        {isOpen ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                      </div>
                    </button>

                    {isOpen && (
                      <div className="px-5 pb-5 pt-1 border-t border-slate-150 text-[11px] leading-relaxed text-slate-500 font-semibold uppercase tracking-normal">
                        {faq.answer}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* CONTACT SUPPORT */}
          <div className="bg-white rounded-3xl shadow-xl border border-slate-100 p-6 md:p-8">
            <div className="mb-6 pb-4 border-b border-slate-100">
              <h2 className="text-lg font-black text-slate-900 uppercase tracking-wide">
                Contact Technical Support
              </h2>
              <p className="text-[10px] font-bold text-slate-450 uppercase tracking-widest mt-0.5">
                Get in touch with operators and system engineers
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-5">
              <div className="p-5 rounded-2xl bg-[#f8fafc] border border-slate-150 shadow-sm flex items-center gap-4 hover:shadow-md hover:border-slate-200 transition-all duration-300">
                <div className="p-3 rounded-xl bg-blue-50 border border-blue-100 text-[#1a6fc4] flex-shrink-0">
                  <Mail className="w-6 h-6" />
                </div>
                <div>
                  <span className="text-[8.5px] font-black text-slate-400 uppercase tracking-widest block">Email Support</span>
                  <a
                    href="mailto:support@neela-ai.com"
                    className="text-xs font-bold text-slate-800 hover:text-[#1a6fc4] transition-colors mt-0.5 block"
                  >
                    support@neela-ai.com
                  </a>
                </div>
              </div>

              <div className="p-5 rounded-2xl bg-[#f8fafc] border border-slate-150 shadow-sm flex items-center gap-4 hover:shadow-md hover:border-slate-200 transition-all duration-300">
                <div className="p-3 rounded-xl bg-blue-50 border border-blue-100 text-[#1a6fc4] flex-shrink-0">
                  <Phone className="w-6 h-6" />
                </div>
                <div>
                  <span className="text-[8.5px] font-black text-slate-400 uppercase tracking-widest block">Technical Hotline</span>
                  <a
                    href="tel:+6281234567890"
                    className="text-xs font-bold text-slate-800 hover:text-[#1a6fc4] transition-colors mt-0.5 block"
                  >
                    +62 812-3456-7890
                  </a>
                </div>
              </div>
            </div>
          </div>

        </main>
      </div>
    </div>
  );
}
