import Sidebar from "../components/Sidebar";
import {
  CircleHelp,
  Radio,
  Cpu,
  BrainCircuit,
  TriangleAlert,
  BarChart3,
  Mail,
  Phone,
  BookOpen,
  Fish,
} from "lucide-react";

export default function HelpPage() {
  const guides = [
    {
      icon: Radio,
      title: "IoT Simulator",
      description:
        "Simulate water quality parameters such as temperature, dissolved oxygen (DO), and pH to test system behavior.",
    },
    {
      icon: Cpu,
      title: "Actuator Control",
      description:
        "Monitor and manually control pond actuators including aerators, feeders, and pumps.",
    },
    {
      icon: BrainCircuit,
      title: "AI Center",
      description:
        "View AI predictions, fish health assessments, and recommendations generated by NEELA AI.",
    },
    {
      icon: TriangleAlert,
      title: "Alerts",
      description:
        "Receive notifications when abnormal water conditions or critical events are detected.",
    },
    {
      icon: BarChart3,
      title: "Analytics",
      description:
        "Analyze historical data, decision trends, and overall aquaculture performance.",
    },
  ];

  const faqs = [
    {
      question:
        "How often is sensor data updated?",
      answer:
        "Sensor values are updated in real time based on the connected IoT devices or simulator settings.",
    },
    {
      question:
        "What does HIGH risk level mean?",
      answer:
        "HIGH risk indicates critical pond conditions that may affect fish health and require immediate action.",
    },
    {
      question:
        "Can I manually override AI recommendations?",
      answer:
        "Yes. Operators can manually control actuators regardless of AI recommendations.",
    },
    {
      question:
        "How is AI confidence calculated?",
      answer:
        "Confidence scores are estimated from the machine learning model performance and historical prediction consistency.",
    },
  ];

  return (
    <div className="md:flex">

      <Sidebar />

      <main className="flex-1 p-4 md:p-10 bg-slate-50 min-h-screen">

        {/* Header */}
        <div className="mb-10">

          <div className="flex items-center gap-4 mb-4">

            <div>
              <h1 className="text-4xl font-bold">

                Help Center

              </h1>

              <p className="text-gray-600 mt-1">

                Learn how to use NEELA AI effectively for smart aquaculture management.

              </p>
            </div>
          </div>

        </div>

        {/* Quick Tips */}
        <div
          className="
            bg-gradient-to-r
            from-cyan-500
            to-blue-600
            rounded-3xl
            p-8
            text-white
            mb-8
          "
        >

          <div className="flex items-center gap-4">

            <Fish size={48} />

            <div>

              <h2 className="text-2xl font-bold">

                Best Practice Tips

              </h2>

              <p className="mt-2 text-white/90">

                Monitor water quality regularly, respond quickly to alerts,
                and use AI recommendations to optimize fish health and pond performance.

              </p>

            </div>

          </div>

        </div>

        {/* User Guides */}
        <div className="bg-white rounded-3xl shadow p-8 mb-8">

          <div className="flex items-center gap-3 mb-6">

            <BookOpen className="text-cyan-600" />

            <h2 className="text-2xl font-bold">

              User Guides

            </h2>

          </div>

          <div className="grid md:grid-cols-2 gap-5">

            {guides.map((guide) => {
              const Icon = guide.icon;

              return (
                <div
                  key={guide.title}
                  className="
                    p-6
                    rounded-2xl
                    border
                    hover:shadow-lg
                    transition-all
                  "
                >

                  <div className="flex items-start gap-4">

                    <div
                      className="
                        p-3
                        rounded-xl
                        bg-cyan-100
                      "
                    >

                      <Icon
                        className="text-cyan-700"
                        size={28}
                      />

                    </div>

                    <div>

                      <h3 className="font-bold text-lg">

                        {guide.title}

                      </h3>

                      <p className="text-gray-600 mt-2">

                        {guide.description}

                      </p>

                    </div>

                  </div>

                </div>
              );
            })}

          </div>

        </div>

        {/* FAQ */}
        <div className="bg-white rounded-3xl shadow p-8 mb-8">

          <h2 className="text-2xl font-bold mb-6">

            Frequently Asked Questions

          </h2>

          <div className="space-y-5">

            {faqs.map((faq) => (

              <div
                key={faq.question}
                className="
                  border
                  rounded-2xl
                  p-5
                "
              >

                <h3 className="font-bold text-lg">

                  {faq.question}

                </h3>

                <p className="text-gray-600 mt-2">

                  {faq.answer}

                </p>

              </div>

            ))}

          </div>

        </div>

        {/* Support */}
        <div className="bg-white rounded-3xl shadow p-8">

          <h2 className="text-2xl font-bold mb-6">

            Contact Support

          </h2>

          <div className="grid md:grid-cols-2 gap-5">

            <div
              className="
                p-6
                rounded-2xl
                bg-slate-50
              "
            >

              <div className="flex items-center gap-3 mb-3">

                <Mail className="text-cyan-600" />

                <h3 className="font-bold">

                  Email Support

                </h3>

              </div>

              <p className="text-gray-600">

                support@neela-ai.com

              </p>

            </div>

            <div
              className="
                p-6
                rounded-2xl
                bg-slate-50
              "
            >

              <div className="flex items-center gap-3 mb-3">

                <Phone className="text-cyan-600" />

                <h3 className="font-bold">

                  Technical Hotline

                </h3>

              </div>

              <p className="text-gray-600">

                +62 812-3456-7890

              </p>

            </div>

          </div>

        </div>

      </main>

    </div>
  );
}
